//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.5.1
//     from Assets/MyControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @MyControls: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @MyControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""MyControls"",
    ""maps"": [
        {
            ""name"": ""PlayerDD"",
            ""id"": ""91e34a32-1707-46c3-b312-e61635dc73d8"",
            ""actions"": [
                {
                    ""name"": ""Skill1"",
                    ""type"": ""Button"",
                    ""id"": ""60dafc0a-7ae4-4ce7-927c-27af1ff90fc5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Skill2"",
                    ""type"": ""Button"",
                    ""id"": ""2cfbfbe9-2849-4eeb-9c82-674114e28cf1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Skill3"",
                    ""type"": ""Button"",
                    ""id"": ""ac09a57b-24fb-41d7-a451-ae04d44649aa"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Skill4"",
                    ""type"": ""Button"",
                    ""id"": ""6eb0ad7b-294e-45c7-b089-ca8fa883f172"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RightShoulder"",
                    ""type"": ""Value"",
                    ""id"": ""8b9ece33-0b34-486f-a8eb-9192a50146b6"",
                    ""expectedControlType"": ""Double"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""LeftShoulder"",
                    ""type"": ""Value"",
                    ""id"": ""8a139e11-fb2f-4436-8da2-38d91f84e464"",
                    ""expectedControlType"": ""Double"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""826230e0-ea6d-4a56-b29d-33f717f0cc7d"",
                    ""path"": ""<DualSenseGamepadHID>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Skill1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9d0eec31-ae45-45be-8e1c-68a924707381"",
                    ""path"": ""<DualShockGamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightShoulder"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3309bec0-5fc3-40ec-bb50-d389e804022d"",
                    ""path"": ""<DualShockGamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controls"",
                    ""action"": ""LeftShoulder"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""81602fa5-6046-42ad-8cb2-04a93a61c310"",
                    ""path"": ""<DualShockGamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controls"",
                    ""action"": ""Skill2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3c69cf71-483d-4df6-a29a-4cb0f545c44c"",
                    ""path"": ""<DualShockGamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controls"",
                    ""action"": ""Skill3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4e7154d0-6da5-4714-81eb-a84a89405268"",
                    ""path"": ""<DualShockGamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controls"",
                    ""action"": ""Skill4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""PlayerBuff"",
            ""id"": ""601ff3d8-6ca8-4745-a3b6-01a3a25caf79"",
            ""actions"": [
                {
                    ""name"": ""New action"",
                    ""type"": ""Button"",
                    ""id"": ""f895cc90-d7a4-440b-9ac5-a1e3f8c46b42"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""0299d4d1-de76-4d05-a0f5-f23133963961"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controls"",
                    ""action"": ""New action"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""MainMenu"",
            ""id"": ""c4bab06e-20a1-45a5-8f96-581eab2c8cc7"",
            ""actions"": [
                {
                    ""name"": ""New action"",
                    ""type"": ""Button"",
                    ""id"": ""e910ccf5-53b2-41a4-8b3f-4f30dae1a676"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""f6bf9da2-d818-43ea-8094-8b7206d570d0"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Controls"",
                    ""action"": ""New action"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Splash"",
            ""id"": ""cf243a72-00b0-44f0-b336-e18288499168"",
            ""actions"": [
                {
                    ""name"": ""TriClick"",
                    ""type"": ""Button"",
                    ""id"": ""3ce0281f-a32c-4ff8-b285-dd4a3814c885"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""d13cdbb2-0ed6-4000-8c31-3b0723f3d3a2"",
                    ""path"": ""<DualShockGamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TriClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Controls"",
            ""bindingGroup"": ""Controls"",
            ""devices"": [
                {
                    ""devicePath"": ""<DualSenseGampadiOS>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // PlayerDD
        m_PlayerDD = asset.FindActionMap("PlayerDD", throwIfNotFound: true);
        m_PlayerDD_Skill1 = m_PlayerDD.FindAction("Skill1", throwIfNotFound: true);
        m_PlayerDD_Skill2 = m_PlayerDD.FindAction("Skill2", throwIfNotFound: true);
        m_PlayerDD_Skill3 = m_PlayerDD.FindAction("Skill3", throwIfNotFound: true);
        m_PlayerDD_Skill4 = m_PlayerDD.FindAction("Skill4", throwIfNotFound: true);
        m_PlayerDD_RightShoulder = m_PlayerDD.FindAction("RightShoulder", throwIfNotFound: true);
        m_PlayerDD_LeftShoulder = m_PlayerDD.FindAction("LeftShoulder", throwIfNotFound: true);
        // PlayerBuff
        m_PlayerBuff = asset.FindActionMap("PlayerBuff", throwIfNotFound: true);
        m_PlayerBuff_Newaction = m_PlayerBuff.FindAction("New action", throwIfNotFound: true);
        // MainMenu
        m_MainMenu = asset.FindActionMap("MainMenu", throwIfNotFound: true);
        m_MainMenu_Newaction = m_MainMenu.FindAction("New action", throwIfNotFound: true);
        // Splash
        m_Splash = asset.FindActionMap("Splash", throwIfNotFound: true);
        m_Splash_TriClick = m_Splash.FindAction("TriClick", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // PlayerDD
    private readonly InputActionMap m_PlayerDD;
    private List<IPlayerDDActions> m_PlayerDDActionsCallbackInterfaces = new List<IPlayerDDActions>();
    private readonly InputAction m_PlayerDD_Skill1;
    private readonly InputAction m_PlayerDD_Skill2;
    private readonly InputAction m_PlayerDD_Skill3;
    private readonly InputAction m_PlayerDD_Skill4;
    private readonly InputAction m_PlayerDD_RightShoulder;
    private readonly InputAction m_PlayerDD_LeftShoulder;
    public struct PlayerDDActions
    {
        private @MyControls m_Wrapper;
        public PlayerDDActions(@MyControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Skill1 => m_Wrapper.m_PlayerDD_Skill1;
        public InputAction @Skill2 => m_Wrapper.m_PlayerDD_Skill2;
        public InputAction @Skill3 => m_Wrapper.m_PlayerDD_Skill3;
        public InputAction @Skill4 => m_Wrapper.m_PlayerDD_Skill4;
        public InputAction @RightShoulder => m_Wrapper.m_PlayerDD_RightShoulder;
        public InputAction @LeftShoulder => m_Wrapper.m_PlayerDD_LeftShoulder;
        public InputActionMap Get() { return m_Wrapper.m_PlayerDD; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerDDActions set) { return set.Get(); }
        public void AddCallbacks(IPlayerDDActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerDDActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerDDActionsCallbackInterfaces.Add(instance);
            @Skill1.started += instance.OnSkill1;
            @Skill1.performed += instance.OnSkill1;
            @Skill1.canceled += instance.OnSkill1;
            @Skill2.started += instance.OnSkill2;
            @Skill2.performed += instance.OnSkill2;
            @Skill2.canceled += instance.OnSkill2;
            @Skill3.started += instance.OnSkill3;
            @Skill3.performed += instance.OnSkill3;
            @Skill3.canceled += instance.OnSkill3;
            @Skill4.started += instance.OnSkill4;
            @Skill4.performed += instance.OnSkill4;
            @Skill4.canceled += instance.OnSkill4;
            @RightShoulder.started += instance.OnRightShoulder;
            @RightShoulder.performed += instance.OnRightShoulder;
            @RightShoulder.canceled += instance.OnRightShoulder;
            @LeftShoulder.started += instance.OnLeftShoulder;
            @LeftShoulder.performed += instance.OnLeftShoulder;
            @LeftShoulder.canceled += instance.OnLeftShoulder;
        }

        private void UnregisterCallbacks(IPlayerDDActions instance)
        {
            @Skill1.started -= instance.OnSkill1;
            @Skill1.performed -= instance.OnSkill1;
            @Skill1.canceled -= instance.OnSkill1;
            @Skill2.started -= instance.OnSkill2;
            @Skill2.performed -= instance.OnSkill2;
            @Skill2.canceled -= instance.OnSkill2;
            @Skill3.started -= instance.OnSkill3;
            @Skill3.performed -= instance.OnSkill3;
            @Skill3.canceled -= instance.OnSkill3;
            @Skill4.started -= instance.OnSkill4;
            @Skill4.performed -= instance.OnSkill4;
            @Skill4.canceled -= instance.OnSkill4;
            @RightShoulder.started -= instance.OnRightShoulder;
            @RightShoulder.performed -= instance.OnRightShoulder;
            @RightShoulder.canceled -= instance.OnRightShoulder;
            @LeftShoulder.started -= instance.OnLeftShoulder;
            @LeftShoulder.performed -= instance.OnLeftShoulder;
            @LeftShoulder.canceled -= instance.OnLeftShoulder;
        }

        public void RemoveCallbacks(IPlayerDDActions instance)
        {
            if (m_Wrapper.m_PlayerDDActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayerDDActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerDDActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerDDActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlayerDDActions @PlayerDD => new PlayerDDActions(this);

    // PlayerBuff
    private readonly InputActionMap m_PlayerBuff;
    private List<IPlayerBuffActions> m_PlayerBuffActionsCallbackInterfaces = new List<IPlayerBuffActions>();
    private readonly InputAction m_PlayerBuff_Newaction;
    public struct PlayerBuffActions
    {
        private @MyControls m_Wrapper;
        public PlayerBuffActions(@MyControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Newaction => m_Wrapper.m_PlayerBuff_Newaction;
        public InputActionMap Get() { return m_Wrapper.m_PlayerBuff; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerBuffActions set) { return set.Get(); }
        public void AddCallbacks(IPlayerBuffActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerBuffActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerBuffActionsCallbackInterfaces.Add(instance);
            @Newaction.started += instance.OnNewaction;
            @Newaction.performed += instance.OnNewaction;
            @Newaction.canceled += instance.OnNewaction;
        }

        private void UnregisterCallbacks(IPlayerBuffActions instance)
        {
            @Newaction.started -= instance.OnNewaction;
            @Newaction.performed -= instance.OnNewaction;
            @Newaction.canceled -= instance.OnNewaction;
        }

        public void RemoveCallbacks(IPlayerBuffActions instance)
        {
            if (m_Wrapper.m_PlayerBuffActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayerBuffActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerBuffActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerBuffActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlayerBuffActions @PlayerBuff => new PlayerBuffActions(this);

    // MainMenu
    private readonly InputActionMap m_MainMenu;
    private List<IMainMenuActions> m_MainMenuActionsCallbackInterfaces = new List<IMainMenuActions>();
    private readonly InputAction m_MainMenu_Newaction;
    public struct MainMenuActions
    {
        private @MyControls m_Wrapper;
        public MainMenuActions(@MyControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Newaction => m_Wrapper.m_MainMenu_Newaction;
        public InputActionMap Get() { return m_Wrapper.m_MainMenu; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MainMenuActions set) { return set.Get(); }
        public void AddCallbacks(IMainMenuActions instance)
        {
            if (instance == null || m_Wrapper.m_MainMenuActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_MainMenuActionsCallbackInterfaces.Add(instance);
            @Newaction.started += instance.OnNewaction;
            @Newaction.performed += instance.OnNewaction;
            @Newaction.canceled += instance.OnNewaction;
        }

        private void UnregisterCallbacks(IMainMenuActions instance)
        {
            @Newaction.started -= instance.OnNewaction;
            @Newaction.performed -= instance.OnNewaction;
            @Newaction.canceled -= instance.OnNewaction;
        }

        public void RemoveCallbacks(IMainMenuActions instance)
        {
            if (m_Wrapper.m_MainMenuActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IMainMenuActions instance)
        {
            foreach (var item in m_Wrapper.m_MainMenuActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_MainMenuActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public MainMenuActions @MainMenu => new MainMenuActions(this);

    // Splash
    private readonly InputActionMap m_Splash;
    private List<ISplashActions> m_SplashActionsCallbackInterfaces = new List<ISplashActions>();
    private readonly InputAction m_Splash_TriClick;
    public struct SplashActions
    {
        private @MyControls m_Wrapper;
        public SplashActions(@MyControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @TriClick => m_Wrapper.m_Splash_TriClick;
        public InputActionMap Get() { return m_Wrapper.m_Splash; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(SplashActions set) { return set.Get(); }
        public void AddCallbacks(ISplashActions instance)
        {
            if (instance == null || m_Wrapper.m_SplashActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_SplashActionsCallbackInterfaces.Add(instance);
            @TriClick.started += instance.OnTriClick;
            @TriClick.performed += instance.OnTriClick;
            @TriClick.canceled += instance.OnTriClick;
        }

        private void UnregisterCallbacks(ISplashActions instance)
        {
            @TriClick.started -= instance.OnTriClick;
            @TriClick.performed -= instance.OnTriClick;
            @TriClick.canceled -= instance.OnTriClick;
        }

        public void RemoveCallbacks(ISplashActions instance)
        {
            if (m_Wrapper.m_SplashActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ISplashActions instance)
        {
            foreach (var item in m_Wrapper.m_SplashActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_SplashActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public SplashActions @Splash => new SplashActions(this);
    private int m_ControlsSchemeIndex = -1;
    public InputControlScheme ControlsScheme
    {
        get
        {
            if (m_ControlsSchemeIndex == -1) m_ControlsSchemeIndex = asset.FindControlSchemeIndex("Controls");
            return asset.controlSchemes[m_ControlsSchemeIndex];
        }
    }
    public interface IPlayerDDActions
    {
        void OnSkill1(InputAction.CallbackContext context);
        void OnSkill2(InputAction.CallbackContext context);
        void OnSkill3(InputAction.CallbackContext context);
        void OnSkill4(InputAction.CallbackContext context);
        void OnRightShoulder(InputAction.CallbackContext context);
        void OnLeftShoulder(InputAction.CallbackContext context);
    }
    public interface IPlayerBuffActions
    {
        void OnNewaction(InputAction.CallbackContext context);
    }
    public interface IMainMenuActions
    {
        void OnNewaction(InputAction.CallbackContext context);
    }
    public interface ISplashActions
    {
        void OnTriClick(InputAction.CallbackContext context);
    }
}
